- hosts: ha
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Install programm
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - gcc
        - openssl-devel
        - readline-devel
        - systemd-devel
        - make
        - pcre-devel
        - tar
        - libselinux-python3

    - name: creates directory 
      file:
        path: /opt/haproxy
        state: directory

    - name: unpack haproxy
      unarchive:
        src: "{{ link }}"
        dest: /opt/haproxy
        mode: '0440'
        extra_opts: --strip-components=1
        remote_src: yes

    - name: Copy dir haproxy error
      ansible.builtin.copy:
       src: /opt/haproxy/examples/errorfiles
       dest: /etc/haproxy/errorfiles
       remote_src: yes
    

    
    
