- hosts: ha
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Install programm
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - gcc
        - openssl-devel
        - readline-devel
        - systemd-devel
        - make
        - pcre-devel
        - tar
        - libselinux-python3

    - name: unpack haproxy
      unarchive:
        src: "{{ link }}"
        dest: /opt/
        mode: '0440'
        remote_src: yes